In [1]:
import pandas as pd
import numpy as np
import re

train = pd.read_csv('./datasets/train_en.csv')
dev = pd.read_csv('./datasets/dev_en.csv')

In [2]:
train.head()

                                       product_title                category
0  Recollections Color Splash Clear Stamps & Stencil    Hobbies & Stationery
1                          soap,lotion scrub set 400  Health & Personal Care
2       Spigen Galaxy S10e Case Tough Armor Gunmetal      Mobile Accessories
3                         Acrylic Lanalon Bright Red    Hobbies & Stationery
4                 303 FLAT SHEET/Blanket 100% cotton           Home & Living

In [3]:
dev.head()

                                  translation_output
0  Oppo A75 A75S A73 Phone Case Soft Rabbit Silic...
1          SOFT 99 Coating Car Wax Strong Water Watt
2              Low Sugar Mango Dry 250g Be The Royal
3  * the culture Japan Imported Round Top Space C...
4  Hello Kitty Sandals Shoes White/Red Children n...

1. punctuation removal 
2. numbers removal 
3. emoji/special characters removal
4. transfer to lowercase
5. tokenization
6. stopwords removal (ignore)

In [4]:
def processor(text):
    text = re.sub(r'[^\w]', ' ', text.lower()) # remove non english words, special characters
    text = re.sub(r'\b\w*[\d]+\w*\b', ' ', text) # remove non digits
    text = ' '.join(text.split()) # remove extra spaces
    return text

In [5]:
train['processed_title'] = train['product_title'].apply(processor)
dev['translation_output'] = dev['translation_output'].apply(processor)

In [6]:
train

,product_title,category,processed_title
0,Recollections Color Splash Clear Stamps & Stencil,Hobbies & Stationery,recollections color splash clear stamps stencil
1,"soap,lotion scrub set 400",Health & Personal Care,soap lotion scrub set
2,Spigen Galaxy S10e Case Tough Armor Gunmetal,Mobile Accessories,spigen galaxy case tough armor gunmetal
3,Acrylic Lanalon Bright Red,Hobbies & Stationery,acrylic lanalon bright red
4,303 FLAT SHEET/Blanket 100% cotton,Home & Living,flat sheet blanket cotton
...,...,...,...
499995,rocker arm roller racing mio,Motors,rocker arm roller racing mio
499996,Secosana (preloved bag),Women's Bags,secosana preloved bag
499997,jag bag,Women's Bags,jag bag
499998,Baby wipes 15 sheets (Alcohol and Paraben Free...,Babies & Kids,baby wipes sheets alcohol and paraben free san...
499999,PRE-LOVED ORIGINAL GREEN FINO BAG,Women's Bags,pre loved original green fino bag

In [8]:
train.to_csv('cleaned_train_en.csv', index=False)
dev.to_csv('cleaned_dev_en.csv', index=False)